services:
  - type: web
    name: mystic-tarot-proxy
    runtime: node
    branch: proxy-anonymous
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: VITE_API_KEYS
        sync: false # Enter keys separated by commas: key1,key2,key3
